/**
 * ApiGateway API
 * ApiGateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ActionReq { 
    action?: ActionReq.ActionEnum;
    postId?: number;
}
export namespace ActionReq {
    export type ActionEnum = 'LIKE' | 'DISLIKE' | 'SAVE' | 'SHARE';
    export const ActionEnum = {
        LIKE: 'LIKE' as ActionEnum,
        DISLIKE: 'DISLIKE' as ActionEnum,
        SAVE: 'SAVE' as ActionEnum,
        SHARE: 'SHARE' as ActionEnum
    };
}
