/**
 * ApiGateway API
 * ApiGateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Posts } from './posts';
import { User } from './user';


export interface Actions { 
    action?: Actions.ActionEnum;
    createdDate?: Date;
    id?: number;
    lastUpdate?: Date;
    posts?: Posts;
    user?: User;
}
export namespace Actions {
    export type ActionEnum = 'LIKE' | 'DISLIKE' | 'SAVE' | 'SHARE';
    export const ActionEnum = {
        LIKE: 'LIKE' as ActionEnum,
        DISLIKE: 'DISLIKE' as ActionEnum,
        SAVE: 'SAVE' as ActionEnum,
        SHARE: 'SHARE' as ActionEnum
    };
}
