/**
 * ApiGateway API
 * ApiGateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClassInfo } from './classInfo';
import { Field } from './field';
import { Type } from './type';


export interface FieldInfo { 
    classInfo?: ClassInfo;
    field?: Field;
    _final?: boolean;
    genericType?: Type;
    name?: string;
    primitive?: boolean;
}
