/**
 * ApiGateway API
 * ApiGateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Actions } from './actions';
import { Categories } from './categories';
import { Hashtag } from './hashtag';
import { User } from './user';


export interface Posts { 
    actions?: Array<Actions>;
    categories?: Categories;
    createdDate?: Date;
    description?: string;
    excerpt?: string;
    hashtags?: Array<Hashtag>;
    id?: number;
    idVideo?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: Date;
    lastUpdate?: Date;
    resetDate?: Date;
    slug?: string;
    thumbnail?: string;
    title?: string;
    type?: number;
    user?: User;
    views?: number;
}
