/**
 * ApiGateway API
 * ApiGateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { URI } from './uRI';


export interface ServiceInstance { 
    host?: string;
    instanceId?: string;
    metadata?: { [key: string]: string; };
    port?: number;
    scheme?: string;
    secure?: boolean;
    serviceId?: string;
    uri?: URI;
}
