/**
 * ApiGateway API
 * ApiGateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Posts } from './posts';


export interface Suggestions { 
    createdDate?: Date;
    description?: string;
    id?: number;
    lastUpdate?: Date;
    name?: string;
    posts?: Array<Posts>;
    slug?: string;
    sort?: number;
    status?: string;
    type?: number;
}
