/**
 * ApiGateway API
 * ApiGateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Actions } from './actions';
import { Posts } from './posts';


export interface User { 
    actions?: Array<Actions>;
    activated: boolean;
    email?: string;
    firstName?: string;
    id?: number;
    imageUrl?: string;
    langKey?: string;
    lastName?: string;
    login: string;
    posts?: Array<Posts>;
    resetDate?: Date;
    subscribeOf?: Array<User>;
    subscribes?: Array<User>;
}
